package eo;
// Generated Jan 6, 2021 9:03:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ApsAdmsPanel generated by hbm2java
 */
public class ApsAdmsPanel  implements java.io.Serializable {


     private Integer panelid;
     private String descr;
     private Set apsAdmAdms = new HashSet(0);

    public ApsAdmsPanel() {
    }

    public ApsAdmsPanel(String descr, Set apsAdmAdms) {
       this.descr = descr;
       this.apsAdmAdms = apsAdmAdms;
    }
   
    public Integer getPanelid() {
        return this.panelid;
    }
    
    public void setPanelid(Integer panelid) {
        this.panelid = panelid;
    }
    public String getDescr() {
        return this.descr;
    }
    
    public void setDescr(String descr) {
        this.descr = descr;
    }
    public Set getApsAdmAdms() {
        return this.apsAdmAdms;
    }
    
    public void setApsAdmAdms(Set apsAdmAdms) {
        this.apsAdmAdms = apsAdmAdms;
    }




}


