package eo;
// Generated Jan 6, 2021 9:03:38 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ApsAdmAdm generated by hbm2java
 */
public class ApsAdmAdm  implements java.io.Serializable {


     private Integer admId;
     private ApsAdmsPanel apsAdmsPanel;
     private ApsAdmsSession apsAdmsSession;
     private ApsGlobClass apsGlobClassBySibling2Class;
     private ApsGlobClass apsGlobClassByClsid;
     private ApsGlobClass apsGlobClassByAdmsForClass;
     private ApsGlobClass apsGlobClassBySibling1Class;
     private ApsGlobCorpsregt apsGlobCorpsregt;
     private ApsGlobGender apsGlobGender;
     private ApsGlobInstitutes apsGlobInstitutes;
     private ApsGlobNationality apsGlobNationality;
     private ApsGlobProf apsGlobProf;
     private ApsGlobProv apsGlobProv;
     private ApsGlobRank apsGlobRank;
     private ApsGlobReligion apsGlobReligion;
     private ApsGlobSec apsGlobSecBySibling2Sec;
     private ApsGlobSec apsGlobSecBySibling1Sec;
     private String srno;
     private Character hsscPremed;
     private Character hsscPreengg;
     private Character hsscIcs;
     private String photograph;
     private Date credate;
     private int status;
     private int userid;
     private String nameInFull;
     private String fname;
     private String fcnic;
     private Date dob;
     private int markofid;
     private String teloff;
     private String mob;
     private String email;
     private String addrPostal;
     private String pgname;
     private String pgcnic;
     private String presentOffice;
     private String addrHome;
     private String addrPgpostal;
     private String teloffPg;
     private String mobPg;
     private String emailPg;
     private String addrPerm;
     private String dname;
     private String dcnic;
     private String dtel;
     private String dmob;
     private String vehno;
     private String erContactno;
     private String erContactname;
     private String sibling1Name;
     private String sibling2Name;

    public ApsAdmAdm() {
    }

	
    public ApsAdmAdm(ApsAdmsPanel apsAdmsPanel, ApsAdmsSession apsAdmsSession, ApsGlobClass apsGlobClassByClsid, ApsGlobCorpsregt apsGlobCorpsregt, ApsGlobGender apsGlobGender, ApsGlobInstitutes apsGlobInstitutes, ApsGlobNationality apsGlobNationality, ApsGlobProf apsGlobProf, ApsGlobProv apsGlobProv, ApsGlobRank apsGlobRank, ApsGlobReligion apsGlobReligion, String srno, Date credate, int status, int userid, String nameInFull, String fname, String fcnic, Date dob, int markofid, String teloff, String mob, String email, String addrPostal) {
        this.apsAdmsPanel = apsAdmsPanel;
        this.apsAdmsSession = apsAdmsSession;
        this.apsGlobClassByClsid = apsGlobClassByClsid;
        this.apsGlobCorpsregt = apsGlobCorpsregt;
        this.apsGlobGender = apsGlobGender;
        this.apsGlobInstitutes = apsGlobInstitutes;
        this.apsGlobNationality = apsGlobNationality;
        this.apsGlobProf = apsGlobProf;
        this.apsGlobProv = apsGlobProv;
        this.apsGlobRank = apsGlobRank;
        this.apsGlobReligion = apsGlobReligion;
        this.srno = srno;
        this.credate = credate;
        this.status = status;
        this.userid = userid;
        this.nameInFull = nameInFull;
        this.fname = fname;
        this.fcnic = fcnic;
        this.dob = dob;
        this.markofid = markofid;
        this.teloff = teloff;
        this.mob = mob;
        this.email = email;
        this.addrPostal = addrPostal;
    }
    public ApsAdmAdm(ApsAdmsPanel apsAdmsPanel, ApsAdmsSession apsAdmsSession, ApsGlobClass apsGlobClassBySibling2Class, ApsGlobClass apsGlobClassByClsid, ApsGlobClass apsGlobClassByAdmsForClass, ApsGlobClass apsGlobClassBySibling1Class, ApsGlobCorpsregt apsGlobCorpsregt, ApsGlobGender apsGlobGender, ApsGlobInstitutes apsGlobInstitutes, ApsGlobNationality apsGlobNationality, ApsGlobProf apsGlobProf, ApsGlobProv apsGlobProv, ApsGlobRank apsGlobRank, ApsGlobReligion apsGlobReligion, ApsGlobSec apsGlobSecBySibling2Sec, ApsGlobSec apsGlobSecBySibling1Sec, String srno, Character hsscPremed, Character hsscPreengg, Character hsscIcs, String photograph, Date credate, int status, int userid, String nameInFull, String fname, String fcnic, Date dob, int markofid, String teloff, String mob, String email, String addrPostal, String pgname, String pgcnic, String presentOffice, String addrHome, String addrPgpostal, String teloffPg, String mobPg, String emailPg, String addrPerm, String dname, String dcnic, String dtel, String dmob, String vehno, String erContactno, String erContactname, String sibling1Name, String sibling2Name) {
       this.apsAdmsPanel = apsAdmsPanel;
       this.apsAdmsSession = apsAdmsSession;
       this.apsGlobClassBySibling2Class = apsGlobClassBySibling2Class;
       this.apsGlobClassByClsid = apsGlobClassByClsid;
       this.apsGlobClassByAdmsForClass = apsGlobClassByAdmsForClass;
       this.apsGlobClassBySibling1Class = apsGlobClassBySibling1Class;
       this.apsGlobCorpsregt = apsGlobCorpsregt;
       this.apsGlobGender = apsGlobGender;
       this.apsGlobInstitutes = apsGlobInstitutes;
       this.apsGlobNationality = apsGlobNationality;
       this.apsGlobProf = apsGlobProf;
       this.apsGlobProv = apsGlobProv;
       this.apsGlobRank = apsGlobRank;
       this.apsGlobReligion = apsGlobReligion;
       this.apsGlobSecBySibling2Sec = apsGlobSecBySibling2Sec;
       this.apsGlobSecBySibling1Sec = apsGlobSecBySibling1Sec;
       this.srno = srno;
       this.hsscPremed = hsscPremed;
       this.hsscPreengg = hsscPreengg;
       this.hsscIcs = hsscIcs;
       this.photograph = photograph;
       this.credate = credate;
       this.status = status;
       this.userid = userid;
       this.nameInFull = nameInFull;
       this.fname = fname;
       this.fcnic = fcnic;
       this.dob = dob;
       this.markofid = markofid;
       this.teloff = teloff;
       this.mob = mob;
       this.email = email;
       this.addrPostal = addrPostal;
       this.pgname = pgname;
       this.pgcnic = pgcnic;
       this.presentOffice = presentOffice;
       this.addrHome = addrHome;
       this.addrPgpostal = addrPgpostal;
       this.teloffPg = teloffPg;
       this.mobPg = mobPg;
       this.emailPg = emailPg;
       this.addrPerm = addrPerm;
       this.dname = dname;
       this.dcnic = dcnic;
       this.dtel = dtel;
       this.dmob = dmob;
       this.vehno = vehno;
       this.erContactno = erContactno;
       this.erContactname = erContactname;
       this.sibling1Name = sibling1Name;
       this.sibling2Name = sibling2Name;
    }
   
    public Integer getAdmId() {
        return this.admId;
    }
    
    public void setAdmId(Integer admId) {
        this.admId = admId;
    }
    public ApsAdmsPanel getApsAdmsPanel() {
        return this.apsAdmsPanel;
    }
    
    public void setApsAdmsPanel(ApsAdmsPanel apsAdmsPanel) {
        this.apsAdmsPanel = apsAdmsPanel;
    }
    public ApsAdmsSession getApsAdmsSession() {
        return this.apsAdmsSession;
    }
    
    public void setApsAdmsSession(ApsAdmsSession apsAdmsSession) {
        this.apsAdmsSession = apsAdmsSession;
    }
    public ApsGlobClass getApsGlobClassBySibling2Class() {
        return this.apsGlobClassBySibling2Class;
    }
    
    public void setApsGlobClassBySibling2Class(ApsGlobClass apsGlobClassBySibling2Class) {
        this.apsGlobClassBySibling2Class = apsGlobClassBySibling2Class;
    }
    public ApsGlobClass getApsGlobClassByClsid() {
        return this.apsGlobClassByClsid;
    }
    
    public void setApsGlobClassByClsid(ApsGlobClass apsGlobClassByClsid) {
        this.apsGlobClassByClsid = apsGlobClassByClsid;
    }
    public ApsGlobClass getApsGlobClassByAdmsForClass() {
        return this.apsGlobClassByAdmsForClass;
    }
    
    public void setApsGlobClassByAdmsForClass(ApsGlobClass apsGlobClassByAdmsForClass) {
        this.apsGlobClassByAdmsForClass = apsGlobClassByAdmsForClass;
    }
    public ApsGlobClass getApsGlobClassBySibling1Class() {
        return this.apsGlobClassBySibling1Class;
    }
    
    public void setApsGlobClassBySibling1Class(ApsGlobClass apsGlobClassBySibling1Class) {
        this.apsGlobClassBySibling1Class = apsGlobClassBySibling1Class;
    }
    public ApsGlobCorpsregt getApsGlobCorpsregt() {
        return this.apsGlobCorpsregt;
    }
    
    public void setApsGlobCorpsregt(ApsGlobCorpsregt apsGlobCorpsregt) {
        this.apsGlobCorpsregt = apsGlobCorpsregt;
    }
    public ApsGlobGender getApsGlobGender() {
        return this.apsGlobGender;
    }
    
    public void setApsGlobGender(ApsGlobGender apsGlobGender) {
        this.apsGlobGender = apsGlobGender;
    }
    public ApsGlobInstitutes getApsGlobInstitutes() {
        return this.apsGlobInstitutes;
    }
    
    public void setApsGlobInstitutes(ApsGlobInstitutes apsGlobInstitutes) {
        this.apsGlobInstitutes = apsGlobInstitutes;
    }
    public ApsGlobNationality getApsGlobNationality() {
        return this.apsGlobNationality;
    }
    
    public void setApsGlobNationality(ApsGlobNationality apsGlobNationality) {
        this.apsGlobNationality = apsGlobNationality;
    }
    public ApsGlobProf getApsGlobProf() {
        return this.apsGlobProf;
    }
    
    public void setApsGlobProf(ApsGlobProf apsGlobProf) {
        this.apsGlobProf = apsGlobProf;
    }
    public ApsGlobProv getApsGlobProv() {
        return this.apsGlobProv;
    }
    
    public void setApsGlobProv(ApsGlobProv apsGlobProv) {
        this.apsGlobProv = apsGlobProv;
    }
    public ApsGlobRank getApsGlobRank() {
        return this.apsGlobRank;
    }
    
    public void setApsGlobRank(ApsGlobRank apsGlobRank) {
        this.apsGlobRank = apsGlobRank;
    }
    public ApsGlobReligion getApsGlobReligion() {
        return this.apsGlobReligion;
    }
    
    public void setApsGlobReligion(ApsGlobReligion apsGlobReligion) {
        this.apsGlobReligion = apsGlobReligion;
    }
    public ApsGlobSec getApsGlobSecBySibling2Sec() {
        return this.apsGlobSecBySibling2Sec;
    }
    
    public void setApsGlobSecBySibling2Sec(ApsGlobSec apsGlobSecBySibling2Sec) {
        this.apsGlobSecBySibling2Sec = apsGlobSecBySibling2Sec;
    }
    public ApsGlobSec getApsGlobSecBySibling1Sec() {
        return this.apsGlobSecBySibling1Sec;
    }
    
    public void setApsGlobSecBySibling1Sec(ApsGlobSec apsGlobSecBySibling1Sec) {
        this.apsGlobSecBySibling1Sec = apsGlobSecBySibling1Sec;
    }
    public String getSrno() {
        return this.srno;
    }
    
    public void setSrno(String srno) {
        this.srno = srno;
    }
    public Character getHsscPremed() {
        return this.hsscPremed;
    }
    
    public void setHsscPremed(Character hsscPremed) {
        this.hsscPremed = hsscPremed;
    }
    public Character getHsscPreengg() {
        return this.hsscPreengg;
    }
    
    public void setHsscPreengg(Character hsscPreengg) {
        this.hsscPreengg = hsscPreengg;
    }
    public Character getHsscIcs() {
        return this.hsscIcs;
    }
    
    public void setHsscIcs(Character hsscIcs) {
        this.hsscIcs = hsscIcs;
    }
    public String getPhotograph() {
        return this.photograph;
    }
    
    public void setPhotograph(String photograph) {
        this.photograph = photograph;
    }
    public Date getCredate() {
        return this.credate;
    }
    
    public void setCredate(Date credate) {
        this.credate = credate;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public int getUserid() {
        return this.userid;
    }
    
    public void setUserid(int userid) {
        this.userid = userid;
    }
    public String getNameInFull() {
        return this.nameInFull;
    }
    
    public void setNameInFull(String nameInFull) {
        this.nameInFull = nameInFull;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getFcnic() {
        return this.fcnic;
    }
    
    public void setFcnic(String fcnic) {
        this.fcnic = fcnic;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public int getMarkofid() {
        return this.markofid;
    }
    
    public void setMarkofid(int markofid) {
        this.markofid = markofid;
    }
    public String getTeloff() {
        return this.teloff;
    }
    
    public void setTeloff(String teloff) {
        this.teloff = teloff;
    }
    public String getMob() {
        return this.mob;
    }
    
    public void setMob(String mob) {
        this.mob = mob;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAddrPostal() {
        return this.addrPostal;
    }
    
    public void setAddrPostal(String addrPostal) {
        this.addrPostal = addrPostal;
    }
    public String getPgname() {
        return this.pgname;
    }
    
    public void setPgname(String pgname) {
        this.pgname = pgname;
    }
    public String getPgcnic() {
        return this.pgcnic;
    }
    
    public void setPgcnic(String pgcnic) {
        this.pgcnic = pgcnic;
    }
    public String getPresentOffice() {
        return this.presentOffice;
    }
    
    public void setPresentOffice(String presentOffice) {
        this.presentOffice = presentOffice;
    }
    public String getAddrHome() {
        return this.addrHome;
    }
    
    public void setAddrHome(String addrHome) {
        this.addrHome = addrHome;
    }
    public String getAddrPgpostal() {
        return this.addrPgpostal;
    }
    
    public void setAddrPgpostal(String addrPgpostal) {
        this.addrPgpostal = addrPgpostal;
    }
    public String getTeloffPg() {
        return this.teloffPg;
    }
    
    public void setTeloffPg(String teloffPg) {
        this.teloffPg = teloffPg;
    }
    public String getMobPg() {
        return this.mobPg;
    }
    
    public void setMobPg(String mobPg) {
        this.mobPg = mobPg;
    }
    public String getEmailPg() {
        return this.emailPg;
    }
    
    public void setEmailPg(String emailPg) {
        this.emailPg = emailPg;
    }
    public String getAddrPerm() {
        return this.addrPerm;
    }
    
    public void setAddrPerm(String addrPerm) {
        this.addrPerm = addrPerm;
    }
    public String getDname() {
        return this.dname;
    }
    
    public void setDname(String dname) {
        this.dname = dname;
    }
    public String getDcnic() {
        return this.dcnic;
    }
    
    public void setDcnic(String dcnic) {
        this.dcnic = dcnic;
    }
    public String getDtel() {
        return this.dtel;
    }
    
    public void setDtel(String dtel) {
        this.dtel = dtel;
    }
    public String getDmob() {
        return this.dmob;
    }
    
    public void setDmob(String dmob) {
        this.dmob = dmob;
    }
    public String getVehno() {
        return this.vehno;
    }
    
    public void setVehno(String vehno) {
        this.vehno = vehno;
    }
    public String getErContactno() {
        return this.erContactno;
    }
    
    public void setErContactno(String erContactno) {
        this.erContactno = erContactno;
    }
    public String getErContactname() {
        return this.erContactname;
    }
    
    public void setErContactname(String erContactname) {
        this.erContactname = erContactname;
    }
    public String getSibling1Name() {
        return this.sibling1Name;
    }
    
    public void setSibling1Name(String sibling1Name) {
        this.sibling1Name = sibling1Name;
    }
    public String getSibling2Name() {
        return this.sibling2Name;
    }
    
    public void setSibling2Name(String sibling2Name) {
        this.sibling2Name = sibling2Name;
    }




}


