package eo;
// Generated Jan 6, 2021 9:03:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ApsGlobNationality generated by hbm2java
 */
public class ApsGlobNationality  implements java.io.Serializable {


     private Integer natid;
     private String descr;
     private Set apsAdmAdms = new HashSet(0);

    public ApsGlobNationality() {
    }

    public ApsGlobNationality(String descr, Set apsAdmAdms) {
       this.descr = descr;
       this.apsAdmAdms = apsAdmAdms;
    }
   
    public Integer getNatid() {
        return this.natid;
    }
    
    public void setNatid(Integer natid) {
        this.natid = natid;
    }
    public String getDescr() {
        return this.descr;
    }
    
    public void setDescr(String descr) {
        this.descr = descr;
    }
    public Set getApsAdmAdms() {
        return this.apsAdmAdms;
    }
    
    public void setApsAdmAdms(Set apsAdmAdms) {
        this.apsAdmAdms = apsAdmAdms;
    }




}


