package eo;
// Generated Jan 6, 2021 9:03:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ApsGlobClass generated by hbm2java
 */
public class ApsGlobClass  implements java.io.Serializable {


     private Integer clsid;
     private String clsname;
     private Set apsAdmAdmsForSibling2Class = new HashSet(0);
     private Set apsAdmAdmsForClsid = new HashSet(0);
     private Set apsAdmAdmsForAdmsForClass = new HashSet(0);
     private Set apsAdmAdmsForSibling1Class = new HashSet(0);

    public ApsGlobClass() {
    }

    public ApsGlobClass(String clsname, Set apsAdmAdmsForSibling2Class, Set apsAdmAdmsForClsid, Set apsAdmAdmsForAdmsForClass, Set apsAdmAdmsForSibling1Class) {
       this.clsname = clsname;
       this.apsAdmAdmsForSibling2Class = apsAdmAdmsForSibling2Class;
       this.apsAdmAdmsForClsid = apsAdmAdmsForClsid;
       this.apsAdmAdmsForAdmsForClass = apsAdmAdmsForAdmsForClass;
       this.apsAdmAdmsForSibling1Class = apsAdmAdmsForSibling1Class;
    }
   
    public Integer getClsid() {
        return this.clsid;
    }
    
    public void setClsid(Integer clsid) {
        this.clsid = clsid;
    }
    public String getClsname() {
        return this.clsname;
    }
    
    public void setClsname(String clsname) {
        this.clsname = clsname;
    }
    public Set getApsAdmAdmsForSibling2Class() {
        return this.apsAdmAdmsForSibling2Class;
    }
    
    public void setApsAdmAdmsForSibling2Class(Set apsAdmAdmsForSibling2Class) {
        this.apsAdmAdmsForSibling2Class = apsAdmAdmsForSibling2Class;
    }
    public Set getApsAdmAdmsForClsid() {
        return this.apsAdmAdmsForClsid;
    }
    
    public void setApsAdmAdmsForClsid(Set apsAdmAdmsForClsid) {
        this.apsAdmAdmsForClsid = apsAdmAdmsForClsid;
    }
    public Set getApsAdmAdmsForAdmsForClass() {
        return this.apsAdmAdmsForAdmsForClass;
    }
    
    public void setApsAdmAdmsForAdmsForClass(Set apsAdmAdmsForAdmsForClass) {
        this.apsAdmAdmsForAdmsForClass = apsAdmAdmsForAdmsForClass;
    }
    public Set getApsAdmAdmsForSibling1Class() {
        return this.apsAdmAdmsForSibling1Class;
    }
    
    public void setApsAdmAdmsForSibling1Class(Set apsAdmAdmsForSibling1Class) {
        this.apsAdmAdmsForSibling1Class = apsAdmAdmsForSibling1Class;
    }




}


