package eo;
// Generated Jan 6, 2021 9:03:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ApsGlobProv generated by hbm2java
 */
public class ApsGlobProv  implements java.io.Serializable {


     private Integer provinceid;
     private String descr;
     private Set apsAdmAdms = new HashSet(0);

    public ApsGlobProv() {
    }

    public ApsGlobProv(String descr, Set apsAdmAdms) {
       this.descr = descr;
       this.apsAdmAdms = apsAdmAdms;
    }
   
    public Integer getProvinceid() {
        return this.provinceid;
    }
    
    public void setProvinceid(Integer provinceid) {
        this.provinceid = provinceid;
    }
    public String getDescr() {
        return this.descr;
    }
    
    public void setDescr(String descr) {
        this.descr = descr;
    }
    public Set getApsAdmAdms() {
        return this.apsAdmAdms;
    }
    
    public void setApsAdmAdms(Set apsAdmAdms) {
        this.apsAdmAdms = apsAdmAdms;
    }




}


