package eo;
// Generated Jan 6, 2021 9:03:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ApsGlobRank generated by hbm2java
 */
public class ApsGlobRank  implements java.io.Serializable {


     private Integer rankid;
     private String descr;
     private Set apsAdmAdms = new HashSet(0);

    public ApsGlobRank() {
    }

    public ApsGlobRank(String descr, Set apsAdmAdms) {
       this.descr = descr;
       this.apsAdmAdms = apsAdmAdms;
    }
   
    public Integer getRankid() {
        return this.rankid;
    }
    
    public void setRankid(Integer rankid) {
        this.rankid = rankid;
    }
    public String getDescr() {
        return this.descr;
    }
    
    public void setDescr(String descr) {
        this.descr = descr;
    }
    public Set getApsAdmAdms() {
        return this.apsAdmAdms;
    }
    
    public void setApsAdmAdms(Set apsAdmAdms) {
        this.apsAdmAdms = apsAdmAdms;
    }




}


