package eo;
// Generated Jan 6, 2021 9:03:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ApsGlobCorpsregt generated by hbm2java
 */
public class ApsGlobCorpsregt  implements java.io.Serializable {


     private Integer srno;
     private String descr;
     private Set apsAdmAdms = new HashSet(0);

    public ApsGlobCorpsregt() {
    }

    public ApsGlobCorpsregt(String descr, Set apsAdmAdms) {
       this.descr = descr;
       this.apsAdmAdms = apsAdmAdms;
    }
   
    public Integer getSrno() {
        return this.srno;
    }
    
    public void setSrno(Integer srno) {
        this.srno = srno;
    }
    public String getDescr() {
        return this.descr;
    }
    
    public void setDescr(String descr) {
        this.descr = descr;
    }
    public Set getApsAdmAdms() {
        return this.apsAdmAdms;
    }
    
    public void setApsAdmAdms(Set apsAdmAdms) {
        this.apsAdmAdms = apsAdmAdms;
    }




}


