package eo;
// Generated Jan 6, 2021 9:03:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ApsGlobReligion generated by hbm2java
 */
public class ApsGlobReligion  implements java.io.Serializable {


     private Integer relid;
     private String descr;
     private Set apsAdmAdms = new HashSet(0);

    public ApsGlobReligion() {
    }

    public ApsGlobReligion(String descr, Set apsAdmAdms) {
       this.descr = descr;
       this.apsAdmAdms = apsAdmAdms;
    }
   
    public Integer getRelid() {
        return this.relid;
    }
    
    public void setRelid(Integer relid) {
        this.relid = relid;
    }
    public String getDescr() {
        return this.descr;
    }
    
    public void setDescr(String descr) {
        this.descr = descr;
    }
    public Set getApsAdmAdms() {
        return this.apsAdmAdms;
    }
    
    public void setApsAdmAdms(Set apsAdmAdms) {
        this.apsAdmAdms = apsAdmAdms;
    }




}


