package eo;
// Generated Jan 6, 2021 9:03:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ApsGlobGender generated by hbm2java
 */
public class ApsGlobGender  implements java.io.Serializable {


     private Integer genderid;
     private String descr;
     private Integer isStudent;
     private Integer isEmp;
     private Set apsAdmAdms = new HashSet(0);

    public ApsGlobGender() {
    }

    public ApsGlobGender(String descr, Integer isStudent, Integer isEmp, Set apsAdmAdms) {
       this.descr = descr;
       this.isStudent = isStudent;
       this.isEmp = isEmp;
       this.apsAdmAdms = apsAdmAdms;
    }
   
    public Integer getGenderid() {
        return this.genderid;
    }
    
    public void setGenderid(Integer genderid) {
        this.genderid = genderid;
    }
    public String getDescr() {
        return this.descr;
    }
    
    public void setDescr(String descr) {
        this.descr = descr;
    }
    public Integer getIsStudent() {
        return this.isStudent;
    }
    
    public void setIsStudent(Integer isStudent) {
        this.isStudent = isStudent;
    }
    public Integer getIsEmp() {
        return this.isEmp;
    }
    
    public void setIsEmp(Integer isEmp) {
        this.isEmp = isEmp;
    }
    public Set getApsAdmAdms() {
        return this.apsAdmAdms;
    }
    
    public void setApsAdmAdms(Set apsAdmAdms) {
        this.apsAdmAdms = apsAdmAdms;
    }




}


