package eo;
// Generated Jan 6, 2021 9:03:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ApsGlobInstitutes generated by hbm2java
 */
public class ApsGlobInstitutes  implements java.io.Serializable {


     private Integer instid;
     private String descr;
     private Set apsAdmAdms = new HashSet(0);

    public ApsGlobInstitutes() {
    }

    public ApsGlobInstitutes(String descr, Set apsAdmAdms) {
       this.descr = descr;
       this.apsAdmAdms = apsAdmAdms;
    }
   
    public Integer getInstid() {
        return this.instid;
    }
    
    public void setInstid(Integer instid) {
        this.instid = instid;
    }
    public String getDescr() {
        return this.descr;
    }
    
    public void setDescr(String descr) {
        this.descr = descr;
    }
    public Set getApsAdmAdms() {
        return this.apsAdmAdms;
    }
    
    public void setApsAdmAdms(Set apsAdmAdms) {
        this.apsAdmAdms = apsAdmAdms;
    }




}


